routes/web.php
<?php

use App\Http\Controllers\ApprovalController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\DoctorController;
use App\Http\Controllers\RujukanKeluarController;
use App\Http\Controllers\RujukanMasukController;
use App\Http\Controllers\BalasanController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [AuthController::class, 'showFormLogin']);
Route::get('login', [AuthController::class, 'showFormLogin'])->name('login');
Route::post('login', [AuthController::class, 'login']);
Route::get('register', [AuthController::class, 'showFormRegister'])->name('register');
Route::post('register', [AuthController::class, 'register']);

Route::group(['middleware' => 'auth'], function () {
    Route::get('home', [HomeController::class, 'index'])->name('home');
    Route::get('logout', [AuthController::class, 'logout'])->name('logout');
});

Route::get('getNumberApproval', [HomeController::class, 'getNumberApproval'])->name('getNumberApproval');

Route::resource('doctors', DoctorController::class);
Route::get('doctors/{id}/download',[DoctorController::class, 'download'])->name('doctors.download');
Route::get('editProfile',[DoctorController::class, 'editProfile'])->name('editProfile');
Route::get('ambilJamRujukan', [DoctorController::class, 'ambilJamRujukan']);
Route::post('updateProfil', [DoctorController::class, 'updateProfil'])->name('updateProfil');
Route::get('inactiveDoctor', [DoctorController::class, 'inactiveDoctor'])->name('inactiveDoctor');

Route::resource('approvals', ApprovalController::class);
Route::get('approveDoctor', [ApprovalController::class, 'approveDoctor'])->name('approveDoctor');

Route::resource('rujukanKeluar', RujukanKeluarController::class);
Route::get('createRujukan',[RujukanKeluarController::class, 'createRujukan'])->name('createRujukan');

Route::resource('rujukanMasuk', RujukanMasukController::class);

Route::resource('balasan', BalasanController::class);
Route::get('viewBalasan', [BalasanController::class, 'viewBalasan'])->name('viewBalasan');

Route::get('send-email','App\Http\Controllers\MailController@sendEmail');

resources/views/home.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Dashboard</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <div class="col-md-12 mt-5">
            <div class="card">
                <div class="card-header">
                    <h3>Dashboard</h3>
                </div>
                <div class="card-body">
                    <h5>Selamat datang di halaman dashboard, <strong>{{ Auth::user()->name }}</strong></h5>
                    <a href="{{ route('logout') }}" class="btn btn-danger">Logout</a>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

resources/views/inactive.blade.php
<!DOCTYPE html>
<html class="loading" lang="en" data-textdirection="ltr">
<!-- BEGIN: Head-->
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta name="description" content="Modern admin is super flexible, powerful, clean &amp; modern responsive bootstrap 4 admin template with unlimited possibilities with bitcoin dashboard.">
    <meta name="keywords" content="admin template, modern admin template, dashboard template, flat admin template, responsive admin template, web app, crypto dashboard, bitcoin dashboard">
    <meta name="author" content="PIXINVENT">
    <title>MERUJUK</title>
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="icon" href="{{asset('images/logo/logo-kecil.png')}}" >
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i%7CQuicksand:300,400,500,700" rel="stylesheet">
    <!-- BEGIN: Vendor CSS-->
    <link rel="stylesheet" type="text/css" href="{{asset('vendors/css/vendors.min.css')}}">
    <!-- END: Vendor CSS-->
    <!-- BEGIN: Theme CSS-->
    <link rel="stylesheet" type="text/css" href="{{asset('css/bootstrap.min.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('css/bootstrap-extended.min.css')}}">

    <link rel="stylesheet" type="text/css" href="{{asset('css/components.min.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('css/plugins/forms/wizard.min.css')}}">
{{--    <link rel="stylesheet" type="text/css" href="{{asset('css/plugins/extensions/toastr.min.css')}}">--}}
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">

</head>
<!-- END: Head-->
<!-- BEGIN: Body-->
<body class="vertical-layout vertical-menu-modern 1-column   blank-page" data-open="click" data-menu="vertical-menu-modern" data-col="1-column">
<!-- BEGIN: Content-->
<div class="app-content content">
    <div class="content-wrapper">
        <div class="content-header row mb-1">
        </div>
        <div class="content-body"><section class="flexbox-container">
                <div class="col-12 d-flex align-items-center justify-content-center">
                    <div class="col-md-4 col-10 box-shadow-2 p-0">
                        <div class="card border-grey border-lighten-3 px-1 py-1 box-shadow-3 m-0">
                            <div class="card-body">
                    <span class="card-title text-center">
            			<img src="{{ asset('images/logo/logo1.png')}}" class="img-fluid mx-auto d-block pt-2" width="300" alt="logo">
            		</span>
                            </div>
                            <div class="card-body text-center">
                                <h3>Hi, {{$currentUser->name}}</h3>
                                <p>You're account is under <strong>Inactive</strong> status.
                                    <br> Please contact the administrator.</p>
                                <div class="mt-2"><i class="la la-cog spinner font-large-2"></i></div>

                                <a href="{{url('logout')}}" class="btn btn-info mt-2">LOGOUT</a>
                            </div>
                            <hr>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</div>

<script src="{{asset('vendors/js/vendors.min.js')}}"></script>
<script src="{{asset('js/core/app-menu.min.js')}}"></script>
<script src="{{asset('js/core/app.min.js')}}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
</body>
<!-- END: Body-->
<!-- Mirrored from pixinvent.com/modern-admin-clean-bootstrap-4-dashboard-html-template/html/ltr/vertical-modern-menu-template/register-simple.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 04 Dec 2019 14:33:49 GMT -->
</html>

resources/views/listBalasan.blade.php
@extends('template')
@section('content')
    <!-- BEGIN: Content -->
    <!-- BEGIN: Content-->
    <div class="app-content content">
        <div class="content-wrapper">
            <div class="content-header row mb-1">
                <div class="content-header-left col-md-6 col-12 mb-2 breadcrumb-new">
                    <h3 class="content-header-title mb-0 d-inline-block">List Balasan</h3>
                    <div class="row breadcrumbs-top d-inline-block">
                        <div class="breadcrumb-wrapper col-12">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="index.html">Home</a>
                                </li>
                                <li class="breadcrumb-item active">List Balasan
                                </li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-body">
                <section id="configuration">
                    <div class="row">
                        <div class="col-12">
                            <div class="card">
                                <div class="card-header pb-0">
                                    <h4 class="card-title">List Balasan</h4>
                                    <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                                    <div class="heading-elements">
                                        <ul class="list-inline mb-0">
                                            <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                            <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                                            <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                                            <li><a data-action="close"><i class="ft-x"></i></a></li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="card-content collapse show">
                                    <div class="card-body card-dashboard">
                                        <div class="table-responsive">
                                            <table id="balasanTable" class="table table-striped table-bordered zero-configuration" width="100%">
                                                <thead>
                                                <tr>
                                                    <th width="30px">No</th>
                                                    <th>Tanggal</th>
                                                    <th>Nama Pasien</th>
                                                    @if ($currentUser->gelar == 'Dokter Gigi' || $currentUser->gelar == 'Dokter Umum')
                                                        <th>Dokter Rujukan</th>
                                                    @endif
                                                    @if ($currentUser->gelar == 'Dokter Spesialis' || $currentUser->gelar == 'Dokter Gigi Spesialis' ||$currentUser->gelar == 'Admin')
                                                        <th>Dokter Perujuk</th>
                                                    @endif
                                                    <th width="250px">Action</th>
                                                </tr>
                                                </thead>
                                                <tbody>

                                                </tbody>
                                                <tfoot>
                                                <tr>
                                                    <th width="30px">No</th>
                                                    <th>Tanggal</th>
                                                    <th>Nama Pasien</th>
                                                    @if ($currentUser->gelar == 'Dokter Gigi' || $currentUser->gelar == 'Dokter Umum')
                                                        <th>Dokter Rujukan</th>
                                                    @endif
                                                    @if ($currentUser->gelar == 'Dokter Spesialis' || $currentUser->gelar == 'Dokter Gigi Spesialis' ||$currentUser->gelar == 'Admin')
                                                        <th>Dokter Perujuk</th>
                                                    @endif
                                                    <th width="250px">Action</th>
                                                </tr>
                                                </tfoot>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>
    <!-- END: Content -->
@endsection
@push('ajax_crud')
    <script type="text/javascript">
        $(function () {

            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            var table = $('#balasanTable').DataTable({
                processing: true,
                serverSide: true,
                ajax: "{{ route('balasan.index') }}",
                columns: [
                    {data: null},
                    {data: 'tanggal', name: 'tanggal'},
                    {data: 'nama_pasien', name: 'nama_pasien'},
                    {data: 'name', name: 'name'},
                    {data: 'action', name: 'action', orderable: false, searchable: false},
                ]
            });

            table.on('draw.dt', function () {
                var info = table.page.info();
                table.column(0, { search: 'applied', order: 'applied', page: 'applied' }).nodes().each(function (cell, i) {
                    cell.innerHTML = i + 1 + info.start;
                });
            });

            $('body').on('click', '.lihatBalasan', function () {
                var id_rujukan = $(this).data('id');
                window.location.href = "{{ route('viewBalasan') }}" +'?id_rujukan='+id_rujukan;
            });

        });
    </script>

@endpush

resources/views/listDoctor.blade.php
@extends('template')
@section('content')
    <!-- BEGIN: Content -->
    <!-- BEGIN: Content-->
    <div class="app-content content">
        <div class="content-wrapper">
            <div class="content-header row mb-1">
                <div class="content-header-left col-md-6 col-12 mb-2 breadcrumb-new">
                    <h3 class="content-header-title mb-0 d-inline-block">Daftar List Dokter</h3>
                    <div class="row breadcrumbs-top d-inline-block">
                        <div class="breadcrumb-wrapper col-12">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="index.html">Home</a>
                                </li>
                                <li class="breadcrumb-item active">Daftar List Dokter
                                </li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-body">
                <section id="configuration">
                    <div class="row">
                        <div class="col-12">
                            <div class="card">
                                <div class="card-header pb-0">
                                    <h4 class="card-title">Daftar List Dokter</h4>
                                    <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                                    <div class="heading-elements">
                                        <ul class="list-inline mb-0">
                                            <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                            <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                                            <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                                            <li><a data-action="close"><i class="ft-x"></i></a></li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="card-content collapse show">
                                    <div class="card-body card-dashboard">
                                        <div class="table-responsive">
                                            <table id="doctorTable" class="table table-striped table-bordered zero-configuration" width="100%">
                                                <thead>
                                                <tr>
                                                    <th width="30px">No</th>
                                                    <th>Nama Dokter</th>
                                                    <th>Gelar</th>
                                                    <th>Tempat Praktik</th>
                                                    <th width="250px">Action</th>
                                                </tr>
                                                </thead>
                                                <tbody>

                                                </tbody>
                                                <tfoot>
                                                <tr>
                                                    <th width="30px">No</th>
                                                    <th>Nama Dokter</th>
                                                    <th>Gelar</th>
                                                    <th>Tempat Praktik</th>
                                                    <th width="250px">Action</th>
                                                </tr>
                                                </tfoot>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>
    <!-- END: Content -->
@endsection
@push('ajax_crud')
    <script type="text/javascript">
        $(function () {

            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            var table = $('#doctorTable').DataTable({
                processing: true,
                serverSide: true,
                ajax: "{{ route('doctors.index') }}",
                columns: [
                    {data: null},
                    {data: 'name', name: 'name'},
                    {data: 'gelar', name: 'gelar'},
                    {data: 'tempat_praktik', name: 'tempat_praktik'},
                    {data: 'action', name: 'action', orderable: false, searchable: false},
                ]
            });

            table.on('draw.dt', function () {
                var info = table.page.info();
                table.column(0, { search: 'applied', order: 'applied', page: 'applied' }).nodes().each(function (cell, i) {
                    cell.innerHTML = i + 1 + info.start;
                });
            });


            $('body').on('click', '.viewDoctor', function () {
                var user_id = $(this).data('id');
                window.location.href = "{{ route('doctors.index') }}" +'/' + user_id +'/edit';
            });

            $('body').on('click', '.viewDoctor', function () {
                var user_id = $(this).data('id');
                window.location.href = "{{ route('doctors.index') }}" +'/' + user_id +'/edit';
            });

            $('body').on('click', '.inactiveDoctor', function () {
                var user_id = $(this).data('id');
                var data = {
                    user_id: user_id,
                }

                swal({
                    title:"Sending data to server",
                    text:"Please wait....",
                    icon: "{{asset('images/logo/loading.gif')}}",
                    buttons: false,
                    closeOnClickOutside: false,
                });

                $.ajax({
                    type: "GET",
                    url: "inactiveDoctor",
                    data: data,
                    success: function (data) {
                        swal.close();
                        table.draw();
                    },
                    error: function (data) {
                        swal.close();
                        console.log('Error:', data);
                    }
                });

            });

        });
    </script>

@endpush

resources/views/login.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login MERUJUK.COM</title>
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="icon" href="{{asset('images/logo/logo-kecil.png')}}" >
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i%7CQuicksand:300,400,500,700" rel="stylesheet">

    <!-- BEGIN: Theme CSS-->
    <link rel="stylesheet" type="text/css" href="{{asset('vendors/css/vendors.min.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('vendors/css/forms/icheck/icheck.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('vendors/css/forms/icheck/custom.css')}}">

    <link rel="stylesheet" type="text/css" href="{{asset('css/bootstrap.min.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('css/bootstrap-extended.min.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('css/colors.min.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('css/components.min.css')}}">

    <link rel="stylesheet" type="text/css" href="{{asset('css/core/menu/menu-types/vertical-menu-modern.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('css/core/colors/palette-gradient.min.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('css/pages/login-register.min.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('css/app.css')}}">

</head>
<body class="vertical-layout vertical-menu-modern 1-column fixed-navbar" data-open="click" data-menu="vertical-menu-modern" data-col="1-column">
<div class="app-content content">
    <div class="content-wrapper">
        <div class="content-header row mb-1">
        </div>
        <div class="content-body">
            <section class="flexbox-container">
                <div class="col-12 d-flex align-items-center justify-content-center">
                    <div class="col-lg-4 col-md-8 col-10 box-shadow-2 p-0">
                        <div class="card border-grey border-lighten-3 m-0">
                            <div class="card-header border-0">
                                <div class="card-title text-center">
{{--                                    <img src="{{asset('images/logo/logo1.png')}}" alt="branding logo" id="logo_login" width="250px">--}}
                                    <img class="asu" id="logo_login" src="{{asset('images/logo/logo1.png')}}" alt="branding logo" >
                                </div>
                                <h6 class="card-subtitle line-on-side text-muted text-center font-small-3 pt-2"><span>Login to MERUJUK</span></h6>
                            </div>
                            <div class="card-content">
                                <div class="card-body">
                                    <form class="form-horizontal" action="{{ route('login') }}" method="post" novalidate>
                                        @csrf
                                        @if(session('errors'))
                                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                                Something is wrong:
                                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                    <span aria-hidden="true">×</span>
                                                </button>
                                                <ul>
                                                    @foreach ($errors->all() as $error)
                                                        <li>{{ $error }}</li>
                                                    @endforeach
                                                </ul>
                                            </div>
                                        @endif
                                        @if (Session::has('success'))
                                            <div class="alert alert-success">
                                                {{ Session::get('success') }}
                                            </div>
                                        @endif
                                        @if (Session::has('error'))
                                            <div class="alert alert-danger">
                                                {{ Session::get('error') }}
                                            </div>
                                        @endif
                                        <fieldset class="form-group position-relative has-icon-left">
                                            <input type="email" class="form-control input-lg" name="email" id="email" placeholder="Email" tabindex="1" required data-validation-required-message= "Please enter your email.">
                                            <div class="form-control-position">
                                                <i class="ft-user"></i>
                                            </div>
                                            <div class="help-block font-small-3"></div>
                                        </fieldset>
                                        <fieldset class="form-group position-relative has-icon-left">
                                            <input type="password" class="form-control input-lg" name="password" id="password" placeholder="Password" tabindex="2" required data-validation-required-message= "Please enter valid passwords.">
                                            <div class="form-control-position">
                                                <i class="la la-key"></i>
                                            </div>
                                            <div class="help-block font-small-3"></div>
                                        </fieldset>

                                        <button type="submit" class="btn btn-info btn-block btn-lg mb-1"><i class="ft-unlock"></i> Login</button>
                                        <p class="text-center">Belum punya akun? <a href="{{ route('register') }}">Register</a> sekarang!</p>
                                    </form>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</div>
{{--    <script src="{{asset('js/scripts/forms/form-login-register.min.js')}}"></script>--}}
</body>
</html>

resources/views/myTestMail.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>websitepercobaan.com</title>
</head>
<body>
<h1>{{ $details['title'] }}</h1>
<p>{{ $details['body'] }}</p>

<p>Thank you</p>
</body>
</html>

resources/views/waiting.blade.php
<!DOCTYPE html>
<html class="loading" lang="en" data-textdirection="ltr">
<!-- BEGIN: Head-->
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta name="description" content="Modern admin is super flexible, powerful, clean &amp; modern responsive bootstrap 4 admin template with unlimited possibilities with bitcoin dashboard.">
    <meta name="keywords" content="admin template, modern admin template, dashboard template, flat admin template, responsive admin template, web app, crypto dashboard, bitcoin dashboard">
    <meta name="author" content="PIXINVENT">
    <title>MERUJUK</title>
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="icon" href="{{asset('images/logo/logo-kecil.png')}}" >
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i%7CQuicksand:300,400,500,700" rel="stylesheet">
    <!-- BEGIN: Vendor CSS-->
    <link rel="stylesheet" type="text/css" href="{{asset('vendors/css/vendors.min.css')}}">
    <!-- END: Vendor CSS-->
    <!-- BEGIN: Theme CSS-->
    <link rel="stylesheet" type="text/css" href="{{asset('css/bootstrap.min.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('css/bootstrap-extended.min.css')}}">

    <link rel="stylesheet" type="text/css" href="{{asset('css/components.min.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('css/plugins/forms/wizard.min.css')}}">
{{--    <link rel="stylesheet" type="text/css" href="{{asset('css/plugins/extensions/toastr.min.css')}}">--}}
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">

</head>
<!-- END: Head-->
<!-- BEGIN: Body-->
<body class="vertical-layout vertical-menu-modern 1-column   blank-page" data-open="click" data-menu="vertical-menu-modern" data-col="1-column">
<!-- BEGIN: Content-->
<div class="app-content content">
    <div class="content-wrapper">
        <div class="content-header row mb-1">
        </div>
        <div class="content-body"><section class="flexbox-container">
                <div class="col-12 d-flex align-items-center justify-content-center">
                    <div class="col-md-4 col-10 box-shadow-2 p-0">
                        <div class="card border-grey border-lighten-3 px-1 py-1 box-shadow-3 m-0">
                            <div class="card-body">
                    <span class="card-title text-center">
            			<img src="{{ asset('images/logo/logo1.png')}}" class="img-fluid mx-auto d-block pt-2" width="300" alt="logo">
            		</span>
                            </div>
                            <div class="card-body text-center">
                                <h3>Hi, {{$currentUser->name}}</h3>
                                <p>You're account is under <strong>verification</strong> process.
                                    <br> Please check back later or contact the administrator.</p>
                                <div class="mt-2"><i class="la la-cog spinner font-large-2"></i></div>

                                <a href="{{url('logout')}}" class="btn btn-info mt-2">LOGOUT</a>
                            </div>
                            <hr>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</div>

<script src="{{asset('vendors/js/vendors.min.js')}}"></script>
<script src="{{asset('js/core/app-menu.min.js')}}"></script>
<script src="{{asset('js/core/app.min.js')}}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
</body>
<!-- END: Body-->
<!-- Mirrored from pixinvent.com/modern-admin-clean-bootstrap-4-dashboard-html-template/html/ltr/vertical-modern-menu-template/register-simple.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 04 Dec 2019 14:33:49 GMT -->
</html>